### ISSUE TITLE
File missing when starting training

### ISSUE THREAD

**Issue by OverRipeThree49** [LUMIA-Group/rasat#1]
So the problem I encountered was that the file named `train_0125_example.json` as stated in the readme file does not exist. I changed the file name to `train_sparc_rasat_small.json` hoping that would circumvent the problem, but another problem arised stating that `No module named 'third_party`.

**Comment by JiexingQi** [comment]
Hi, @OverRipeThree49 , Did you run 
```
git submodule update --init --recursive
```
successfully, please check the third_party floder when you have finished this command.

**Comment by OverRipeThree49** [comment]
@JiexingQi Sorry, forgot that command.
