### ISSUE TITLE
Possible error in adding new tokens to t5_tokenizer

### ISSUE THREAD

**Issue by FruVirus** [LUMIA-Group/rasat#11]
Is the extra space supposed to be here for the `<=` and `<` tokens for the `t5_tokenizer`?

https://github.com/LUMIA-Group/rasat/blob/b912ce8e747e9d6a661fdef73a19818bab4b3508/seq2seq/preprocess/lgerels2t5rels_changeOrder.py#L433

**Comment by JiexingQi** [comment]
We add these two tokens to consist with the tokenizer in run_seq2seq.py as 
https://github.com/LUMIA-Group/rasat/blob/b912ce8e747e9d6a661fdef73a19818bab4b3508/seq2seq/run_seq2seq.py#L155

**Comment by FruVirus** [comment]
i see---in either case, i ran evaluation on spider dataset both with and without the extra spacing and it doesn't seem to make a difference in terms of the accuracy.

**Comment by JiexingQi** [comment]
There are only a few examples contain "<" or "<=" in this dataset, I guess this is why it was not affected.

**Comment by FruVirus** [comment]
that makes sense. i guess i was originally curious as to why the extra space is there---i.e., why is it ` <=` instead of `<=`.

**Comment by JiexingQi** [comment]
well, we just keep what PICARD author does and do not change it,
https://github.com/ServiceNow/picard/blob/6a252386bed6d4233f0f13f4562d8ae8608e7445/seq2seq/run_seq2seq.py#L140
