### ISSUE TITLE
Possible error in `generate_relations`

### ISSUE THREAD

**Issue by tonyzhao6** [LUMIA-Group/rasat#14]
https://github.com/LUMIA-Group/rasat/blob/961a6974e0e5264ded56c9ced106ac8d63c0e725/seq2seq/preprocess/lgerels2t5rels_changeOrder.py#L378

In the `for edge in edges` loop, `db_t5_src_id` and `db_t5_dst_id` will always be empty lists since they are reassigned _**after**_ the `try-except` block. I believe the intention here was to assign these two lists _**before**_ the `try-except` block.

**Comment by Monstarrr** [comment]
Thanks for ur debugging! We will check the code again and the performance might be even higher then.
