### ISSUE TITLE
Model weight missing.

### ISSUE THREAD

**Issue by linxin6** [LUMIA-Group/rasat#17]
Hello author, I found that the model weights were missing when I tried to reproduce your results directly using Docker. Can you share the model weights with me?

**Comment by JiexingQi** [comment]
Hi, all models are in huggingface: https://huggingface.co/Jiexing

**Comment by linxin6** [comment]
Thanks

**Comment by linxin6** [comment]
Hello, may I ask if you can share the predicted SQL that you finally ran on the validation set? Replicating your work is too time-consuming for me as my server does not have a GPU.

**Comment by linxin6** [comment]
Hello, may I ask if you can share the predicted SQL that you finally ran on
the validation set? Replicating your work is too time-consuming for me as
my server does not have a GPU.

JiexingQi ***@***.***> 于2023年6月7日周三 18:08写道：
