### ISSUE TITLE
Hello, I have a small question for you. What is the meaning of the sequence number after the model configuration file?

### ISSUE THREAD

**Issue by kanseaveg** [LUMIA-Group/rasat#20]
Hello, I have a small question for you. What is the meaning of the sequence number after the model configuration file?

![image](https://github.com/LUMIA-Group/rasat/assets/80022154/d414eec2-fb6e-427c-ab58-a3f8110b656e)

In the Spider dataset, there are also such configuration file extensions.
![image](https://github.com/LUMIA-Group/rasat/assets/80022154/8e3848b8-3f45-4b7d-a4fa-5ff746fb4ac3)

I would like to ask what these mean, and if I use t5-small for training, which configuration file should I use for evaluation?

Wishing you good health during the Dragon Boat Festival and success in your work. Best regards.

**Comment by JiexingQi** [comment]
Hi, @kanseaveg , this number means the global steps. Different number means different checkpoint.

**Comment by kanseaveg** [comment]
Sincerely thank you for your answer.
I will give the t5-small version a try.
Once again, thank you, my dear Q classmate.
