### ISSUE TITLE
Question about Question Dependency Structure relation

### ISSUE THREAD

**Issue by FruVirus** [LUMIA-Group/rasat#9]
Hello there,

First of all, great work you guys! I'm really excited to understand and evaluate your model on other datasets. 

My question is simply: How is Question Dependency Structure relation different from regular self-attention? According to Figure 2 in the paper, it seems that this relation serves the same purpose as vanilla self-attention. Can you expand upon this relation concept?

**Comment by JiexingQi** [comment]
In fact, the regular self-attention may learn the dependency relation in an implicit way, as we can see in the Table 9 and Table 10, the results can be improved by using relation-aware self-attention, especially for small model.
